<?php

use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\views\Views;
use Drupal\Core\Site\Settings;
use Symfony\Component\HttpFoundation\RedirectResponse;
use GuzzleHttp\Exception\ClientException;

function data_router_form_alter(&$form,&$form_state,&$form_id){
  if($form_id == 'user_login_form'){
    $form['actions']['submit']['#attributes'] =  [
      'class' => ['btn btn--stroke full-width'],
    ];
    $form['actions']['submit']['#submit'][] =  'login_redirect';
    $form['#validate'][] = 'validate_captcha';
  }

  if($form_id == 'devel_admin_settings_form'){}

  if($form_id == 'node_places_form'){
    $form['status']['widget']['value']['#default_value'] = FALSE;
    $form['actions']['submit']['#submit'][] = 'send_email_add';
  }

  if($form_id == 'node_places_edit_form'){
    $form['actions']['submit']['#submit'][] = 'send_email_edit';
  }
}

function send_email_add(&$form,&$form_state){
  $values = $form_state->getValues();
  $url    = $values['path'][0]['alias'];
  $nid    = $values['nid'];

  // $roles = array_values($user->getRoles());
  $user  = \Drupal::currentUser();
  $email = $user->getEmail();

  $type  = 'add_data';
  sendEmail($type,$email);

}

function send_email_edit(&$form,&$form_state){
  $values = $form_state->getValues();
  $url    = $values['path'][0]['alias'];
  $nid    = $values['nid'];
  $status = $values['status'];
  
  $user  = \Drupal::currentUser();
  $email = $user->getEmail();

  $type  = 'edit_data';
  sendEmail($type,$email);
}

function sendEmail($type,$email){
  $node =  \Drupal::service('entity_type.manager')
          ->getStorage('node')
          ->loadByProperties(['type'=>'config','field_config_name'=>$type]);
  $node    = array_values($node)[0];
  $message = $node->field_message->value;
  $subject = $node->field_subject->value;

  return \Drupal::service('data_router.mail')
          ->setMail($email)
          ->setSubject($subject)
          ->setMessage($message)
          ->send();
}


function login_redirect($form,$form_state){
  $input    = $form_state->getUserInput();
  $name     = $input['name'];
  $pass     = $input['pass'];
  $user     = \Drupal::service('entity_type.manager')->getStorage('user')->loadByProperties(['name' => $name]);
  user_login_finalize(reset($user));
  $url = Url::fromRoute('<front>');
  $form_state->setRedirectUrl($url);
  \Drupal::messenger()->addMessage('Welcome '.$name);
}



function validate_captcha($form,$form_state){
  $input   = $form_state->getUserInput();
  $token   = $input['g-recaptcha-response'];
  if(empty($token)){
    return $form_state->setErrorByName('captcha','Warning Please use Captcha');
  }

  $response = \Drupal::service('data_router.account')->setToken($token)->checkCaptcha();
  if($response == false){
    return $form_state->setErrorByName('captcha','Sorry , Youre Captcha was expired. Please Login again');
  }
}

 function data_router_theme($existing, $type, $theme, $path){
    return [
      'result' => [
        'variables' => ['data' => NULL],
      ],
      'qr' => [
        'variables' => ['data' => NULL],
      ],
      'student' => [
        'variables' => ['data' => NULL],
      ],
    ];
 } 