<?php

/**
 * @file
 * Contains csv_importer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\advanced_scheduler\Controller\SchedulerModeration;
/**
 * Implements hook_help().
 */
function csv_importer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.csv_importer':
      $output = '';
      $output .= '<h3>' . t('CSV Importer') . '</h3>';
      $output .= '<p>' . t('Import content from CSV files, by default it supports <strong>Node</strong>, <strong>Taxonomy</strong> and <strong>User</strong> import.') . '</p>';
      $output .= '<h4>' . t('Usage') . '</h4>';
      $output .= '<ul>';
      $output .= '<li>' . t('Navigate <a href="@uri" target="_blank">here</a>', ['@uri' => Url::fromRoute('csv_importer.form')->toString()]) . '</li>';
      $output .= '<li>' . t('Choose entity type') . '</li>';
      $output .= '<li>' . t('Choose entity bundle (if any)') . '</li>';
      $output .= '<li>' . t('Choose CSV file') . '</li>';
      $output .= '<li>' . t('Press <strong>CSV import</strong>') . '</li>';
      $output .= '</ul>';
      $output .= '<h4>' . t('Documentation') . '</h4>';
      $output .= '<a href="https://www.drupal.org/docs/8/modules/csv-importer" target="_blank">' . 'https://www.drupal.org/docs/8/modules/csv-importer' . '</a>';
      return $output;
  }
}

/**
 * Implements form_alter().
 */
function csv_importer_form_alter(&$form,FormStateInterface $form_state, $form_id) {
  if($form_id == 'csv_importer_form'){
    $form['import']['#validate'][] = 'csv_importer_validate';

    
  }
}

// Validate callback for csv importer
function csv_importer_validate($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  if(!empty($values)){
    if (isset($form_state->getUserInput()['entity_type_bundle'])) {
      $entity_type_bundle = $form_state->getUserInput()['entity_type_bundle'];
    }
    $csv       = $values['csv'];
    if(empty($entity_type_bundle)){
      $form_state->setErrorByName('entity_type_bundle', 'Entity bundle is required.');
    }else{
      if($values['op'] == 'Import'){
        if(empty($csv)) {
          $form_state->setErrorByName('csv', 'CSV file is required.');
        }
      }
    }
  }
}
