_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_importer: 0
  ctools: 0
  data_router: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  google_analytics: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  image_class: 0
  imce: 0
  jsonapi: 0
  link: 0
  link_class: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  renify_commander: 0
  rest: 0
  rest_api_access_token: 0
  schema_article: 0
  schema_metatag: 0
  schema_web_page: 0
  schema_web_site: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  seven: 0
  renify: 0
  adminimal_theme: 0
  renify_dashboard: 0
  rboot: 0
profile: standard
