_core:
  default_config_hash: dwMYPgAnj9KBO77SLEv9Z42NDJAbuxe0uU9eGC8qw3M
account: 'G-CR2YS6JQRB,UA-163503291-2'
domain_mode: 2
cross_domains: 'www.renifysite.com,https://gcash.renifysite.com/,https://renifysite.com,www.renifysite.com/'
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role_mode: 0
  user_role_roles: {  }
  user_account_mode: 1
track:
  outbound: true
  mailto: true
  tel: true
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: true
  linkid: true
  urlfragments: true
  userid: false
  messages:
    status: status
    warning: warning
    error: error
  site_search: true
  adsense: true
  displayfeatures: true
privacy:
  anonymizeip: true
custom:
  parameters:
    dimension1:
      type: dimension
      name: utm_source
      value: '[site:url]'
    metric1:
      type: metric
      name: utm_campaign
      value: '[node:title]'
codesnippet:
  create: {  }
  before: ''
  after: ''
translation_set: false
cache: true
debug: false
