_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
abs_urls: true
admin_theme: true
roles_profiles:
  administrator:
    public: admin
    private: admin
  moderator:
    public: member
    private: member
