favicon:
  mimetype: image/vnd.microsoft.icon
  path: favicon.ico
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
