_core:
  default_config_hash: 1HsKvzB8TdYnw0zBqZtxDsIyOOqugKX4ZxPDweI3ZxA
app_id: '528985515415584'
secret_token: 32473e7c825dbe076b2bac72120f78ce
redirect_uri: 'https://renifysite.com'
access_token: IGQVJVNEVBRkExWWFyV1BxYW9OYXk4MmQ2V0FCZAHlsWk5iT0s5eHpvZAEZA1TDBfUEctV1VKV2l3TF9fVDJIQ0VsV2NWczI3ZAlloWXVFX1NUcTBJZAVNjX2l1YjBnOUo5ZA1d1blJsbjc1NDNOcTF3MzQ3bEtOR1RES3NXSkhV
access_token_long: IGQVJWaTV0TFptbzliVnlsSFB3R2E0SW9CTm9SdTg4VG5DSHZAqUG9TRFZAWOUdRTUU4WXBpNm1tcEVZAdURRTC04eFNtWWtDak9sQ0hianhLZAHYxUFZAqWGhWSDBFdG1KMlR4VWJnS1hB
user_id: 17841401288894336
